# ML-02 — Research Question and Provisional Lane

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

### Content Refresh Prioritization

I selected the Content Refresh Prioritization lane.

I chose this lane because the dataset contains information about existing content pages and their characteristics. The goal is to identify which pages may benefit most from updating or improving.

This problem connects data analysis with a real business decision: deciding which content should receive SEO improvement efforts first. Instead of randomly updating pages, data can help prioritize pages where the expected impact may be higher.

The objective is not only to build a model, but to support better decision-making by identifying opportunities and reducing wasted effort.

## Research Question

### Question

Which content pages should be prioritized for refresh to improve their potential performance?

### Decision

The decision is which pages the SEO/content team should update first.

### Unit of Analysis

The unit of analysis is an individual webpage/content item.

### Output

The output will be a ranked list of pages based on their potential need or opportunity for content refresh.

### Action

Based on this recommendation, the content team can:

- Update outdated information
- Improve page structure and readability
- Optimize content for relevant search intent
- Refresh keywords and metadata

### Cost of a Wrong Recommendation

A wrong recommendation could result in:

- Spending time updating pages with low impact
- Missing opportunities on pages with higher potential
- Reduced efficiency of the content team

### Why Data/ML Can Help

Data and machine learning can identify patterns across many pages that may not be obvious through manual review. This can help prioritize content refresh decisions using evidence from historical data.

## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

In [18]:
import pandas as pd

df = pd.read_csv("flyrank-ml-internship/data/raw/content_refresh_anonymized.csv")

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

df.head()

Number of rows: 30000
Number of columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [14]:
df.columns.tolist()

['content_id',
 'client_id',
 'search_volume',
 'competition',
 'competition_level',
 'cpc',
 'content_type',
 'main_intent',
 'word_count',
 'char_count',
 'provider_used',
 'model_used',
 'impressions_90d',
 'clicks_90d',
 'pageviews_90d',
 'sessions_90d',
 'users_90d',
 'engaged_sessions_90d',
 'ai_sessions_90d',
 'scroll_events_90d',
 'days_with_impressions',
 'days_with_sessions',
 'impressions_last_30d',
 'clicks_last_30d',
 'sessions_last_30d',
 'impressions_prev_30d',
 'clicks_prev_30d',
 'sessions_prev_30d',
 'content_age_days',
 'age_tier',
 'age_tier_order',
 'days_since_last_update',
 'freshness_tier',
 'word_count_tier',
 'char_count_tier',
 'ctr',
 'avg_position',
 'engagement_rate',
 'scroll_rate',
 'ai_traffic_pct',
 'impression_tier',
 'position_tier',
 'trend_direction',
 'trend_pct']

In [15]:
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [21]:
df.shape

(30000, 44)

## Quick Look at the Data

The dataset contains **30000 content records** and **44 features**.

This indicates there are enough examples and attributes to explore patterns related to content refresh opportunities.

The dataset provides useful signals that can support prioritization decisions.

## Careful Words: What I Can and Can't Claim

### What I can claim:
- I can identify patterns in existing content data.
- I can rank pages based on available signals.
- I can support content prioritization decisions.

### What I cannot claim:
- I cannot guarantee that refreshing content will increase traffic.
- I cannot prove causation from historical data alone.
- External factors may also affect content performance.

## Self-Check

- Selected one clear lane.  
- Defined a useful business question.  
- Identified the decision being improved.  
- Explained possible actions.  
- Explained the cost of a wrong recommendation.  
- Used real data numbers.  
- Explained why ML can help.  
- Avoided unsupported claims.